version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - auth-network

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "5000:5000"
    networks:
      - auth-network
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./src:/app/src

networks:
  auth-network:
    driver: bridge
